### ISSUE TITLE
cortical layer data from BigBrainWarp

### ISSUE THREAD

**Issue by Stonlee** [netneurolab/shafiei_megdynamics#1]
Hello, 
Thanks first for you providing the open codes. I'm running the script "scpt_prepare_microscdata.py".  I downloaded the document of cortical layer data from BigBrainWarp (BBW_BigData.zip). However, “tpl-fsaverage_hemi-L_den-164k_desc-layer%s_thickness.shape.gii‘ are missing in "/spaces/tpl-fsaverage/" directory.
Where Can I download these files?
Thanks.

**Comment by gshafiei** [comment]
Hello! Thank you for your interest in our project! It seems like the BigBrainWarp downloaded data folder doesn't include the "layer thickness" in the "fsaverage" space anymore. However, you can use BigBrainWarp package to transform the layer thickness data from "bigbrain" space to "fsaverage" space, setting the density of output mesh ("out_dens") to 164. Detailed documentation on how to apply this transformation is available here: https://bigbrainwarp.readthedocs.io/en/latest/pages/scripts.html . I hope this helps! Thank you!
